### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by WarrierRajeev** [dparker2/py-expiring-dict#2]
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if hasattr(collections, 'MutableSet'): # Only supported in Python 2.6+

**Comment by WarrierRajeev** [comment]
I've made changes in a branch locally. If you give me permissions, I'll push the branch and submit a PR. You can review it and simply merge

**Comment by dparker2** [comment]
@WarrierRajeev So sorry I did not see this until now, I clearly need to update my notifications. Feel free to fork the repo and open a PR from your fork though! I can update the import though soon if you aren't able to get to it

**Comment by WarrierRajeev** [comment]
I have submitted a PR

**Comment by dparker2** [comment]
fixed in #3, v1.0.1 published. thanks a lot!

**Comment by dparker2** [comment]
looks like the `blist` dependency had the same issue, actually. replaced it with `sortedcontainers` in `1.1.0` so that 3.8 is fully supported

**Comment by WarrierRajeev** [comment]
Awesome! Glad I could help. :)
